name: check code quality

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
  
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5 
      with:
        python-version: ${{ matrix.python-version }}

    - name: Check style with ruff
      run: |
        pip install -U ruff==0.4.9
        ruff check ../gptqmodel ../examples ../tests ../setup.py --exit-non-zero-on-fix
