name: check code quality

on:
  push:
    branches: [ main ]
    paths:
      - "gptqmodel/**.py"
      - "tests/**.py"
      - "examples/**.py"
      - "setup.py"

  pull_request:
    branches: [ main ]
    paths:
      - "gptqmodel/**.py"
      - "tests/**.py"
      - "examples/**.py"
      - "setup.py"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
  
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5 
      with:
        python-version: ${{ matrix.python-version }}

    - name: Check style with ruff
      run: |
          cd format
          ./format.sh
