name: Run tests

on:
  push:
    branches:
      - csy-runner
  repository_dispatch:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  DAY_OF_WEEK: Monday
  CUDA_DEVICE_ORDER: PCI_BUS_ID
  CUDA_VISIBLE_DEVICES: 0

jobs:
  build:
    runs-on: self-hosted
    container:
      image: pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile
        run: |
          pip install pytest ninja parameterized
          pip install -v --no-build-isolation .
          cd tests

      - name: test_lm_head.py
        run: |
          pytest test_lm_head.py

      - name: test_perplexity.py
        run: |
          pytest test_perplexity.py

      - name: test_q4_cuda.py
        run: |
          pytest test_q4_cuda.py

      - name: test_q4_exallama.py
        run: |
          pytest test_q4_exallama.py

      - name: test_q4_exallama_v2.py
        run: |
          pytest test_q4_exallama_v2.py

      - name: test_q4_marlin.py
        run: |
          pytest test_q4_marlin.py

      - name: test_q4_triton.py
        run: |
          pytest test_q4_triton.py

      - name: test_quant_formats.py
        run: |
          pytest test_quant_formats.py

      - name: test_repacking.py
        run: |
          pytest test_repacking.py

      - name: test_serialization.py
        run: |
          pytest test_serialization.py

      - name: test_sharded_loading.py
        run: |
          pytest test_sharded_loading.py

      - name: test_triton.py
        run: |
          pytest test_triton.py

        
