name: Run tests

on:
  push:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Install pip depends
        run: |
          pip install parameterized protobuf

      - name: Compile
        run: |
          pip install -vvv --no-build-isolation -e .

      - name: Run tests
        run: |
          cd tests
          pytests -v 
