name: Run tests

on:
  push:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: modelcloud/gptqmodel:github-ci-v1

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install test dependencies
        run: |
          pip install -U parameterized protobuf ninja
          
      - name: Compile
        run: |
          pip install -v --no-build-isolation .

      - name: Run tests
        run: |
          pytest test_lm_head.py
          pytest test_perplexity.py
          pytest test_q4_cuda.py
          pytest test_q4_exallama.py
          pytest test_q4_exallama_v2.py
          pytest test_q4_marlin.py
          pytest test_q4_triton.py
          pytest test_quant_formats.py
          pytest test_repacking.py
          pytest test_serialization.py
          pytest test_sharded_loading.py
          pytest test_triton.py
