name: Unit Tests

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      repo:
        description: 'GitHub repo {owner}/{repo}'
        required: false
        default: ''
      ref:
        description: 'Branch, Tag or Commit SHA'
        required: false
        default: ''
      test_names:
        description: 'Input Test(s) to Run (default all)'
        required: false
        default: ''

env:
  CUDA_DEVICE_ORDER: PCI_BUS_ID
  CPU_TEST_FILES: "test_qbits.py"

jobs:
  build:
    runs-on: [self-hosted, intel]
    container:
      image: 10.0.13.31:5000/modelcloud/gptqmodel:github-ci-v2
    steps:
      - name: Checkout Codes
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}

      - name: Compile
        shell: bash
        run: python setup.py bdist_wheel

      - name: Show dist folder
        run: ls -alh dist

      - name: Upload to artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  gpu-test-files:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.files.outputs.files }}
    steps:
      - name: Checkout Codes
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}

      - name: List files
        id: files
        shell: bash
        run: |
          script="
          import json
          import os
          cpu_file_list = [file.strip().removesuffix('.py') for file in '${CPU_TEST_FILES}'.split(',')]
          test_files_list = [file.strip().removesuffix('.py') for file in '${{ github.event.inputs.test_names }}'.split(',') if file.strip()]
          all_tests = [file.removesuffix('.py') for file in os.listdir('tests/') if file.startswith('test_') and file.endswith('.py')]
          all_tests = [file for file in all_tests if file not in cpu_file_list]
          result = [file for file in all_tests if file in test_files_list] if test_files_list else all_tests
          print(json.dumps(result))
          "
          result=$(python3 -c "$script")
          echo "files=$result" >> "$GITHUB_OUTPUT"
          echo "Test files: $result"

  cpu-test-files:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.files.outputs.files }}
    steps:
      - name: Checkout Codes
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}

      - name: List files
        id: files
        shell: bash
        run: |
          script="
          import json
          cpu_file_list = [file.strip().removesuffix('.py') for file in '${CPU_TEST_FILES}'.split(',') if file.strip()]
          test_files_list = [file.strip().removesuffix('.py') for file in '${{ github.event.inputs.test_names }}'.split(',') if file.strip()]
          result = [file for file in cpu_file_list if file in test_files_list] if test_files_list else cpu_file_list
          print(json.dumps(result))
          "
          result=$(python3 -c "$script")
          echo "files=$result" >> "$GITHUB_OUTPUT"
          echo "Test files: $result"

  test_gpu:
    needs:
      - build
      - gpu-test-files
    runs-on: self-hosted
    container:
      image: 10.0.13.31:5000/modelcloud/gptqmodel:github-ci-v2
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        test_script: ${{ fromJSON(needs.gpu-test-files.outputs.files) }}

    steps:
      - name: Checkout Codes
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}

      - name: Show folder
        run: |
          ls -alh . || true
          ls -alh dist || true
          rm -rf dist/* || true

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Show dist folder
        run: ls -alh dist || true

      - name: Install wheel
        shell: bash
        run: pip install dist/*.whl parameterized uvicorn

      - name: Check platform
        shell: bash
        run: |
          vendor=$(lscpu | grep 'Vendor ID')
          if [[ $vendor == *"Intel"* ]]; then
            ip="10.0.23.62"
          else
            ip="10.0.13.31"
          fi
          echo "GPU_IP=$ip" >> $GITHUB_ENV

      - name: Find suitable GPU
        shell: bash
        run: |
          gpu_id=-1

          while [ "$gpu_id" -lt 0 ]; do
            gpu_id=$(curl -s "http://${{ env.GPU_IP }}/gpu/get?id=${{ github.run_id }}")

            if [ "$gpu_id" -lt 0 ]; then
              echo "No available GPU, waiting 5 seconds..."
              sleep 5
            else
              echo "Allocated GPU ID: $gpu_id"
            fi
          done
          echo "CUDA_VISIBLE_DEVICES=$gpu_id" >> $GITHUB_ENV
          echo "CUDA_VISIBLE_DEVICES set to $gpu_id"

      - name: Run tests
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, matrix.test_script) }}
        run: pytest --durations=0 tests/${{ matrix.test_script }}.py

      - name: Release GPU
        if: always()
        shell: bash
        run: curl -X GET "http://${{ env.GPU_IP }}/gpu/release?id=${{ github.run_id }}&gpu=$CUDA_VISIBLE_DEVICES"

  test_cpu:
    needs:
      - build
      - cpu-test-files
    runs-on: [self-hosted, intel]
    container:
      image: 10.0.13.31:5000/modelcloud/gptqmodel:github-ci-v2
    strategy:
      fail-fast: false
      matrix:
        test_script:  ${{ fromJSON(needs.cpu-test-files.outputs.files) }}

    steps:
      - name: Checkout Codes
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ github.event.inputs.ref }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Install wheel
        shell: bash
        run: |
          pip install dist/*.whl

      - name: Run tests
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, matrix.test_script) }}
        run: pytest --durations=0 tests/${{ matrix.test_script }}.py
