name: Unit Tests (GPU)

on:
  push:
  repository_dispatch:
  workflow_dispatch:

env:
  CUDA_DEVICE_ORDER: PCI_BUS_ID

jobs:
  build:
    runs-on: self-hosted
    container:
      image: modelcloud/gptqmodel:github-ci-v1
      volumes:
        - /tmp/${{ github.run_id }}_1:/data_1:rw
        - /tmp/${{ github.run_id }}_2:/data_2:rw
    steps:
      - name: Checkout Codes
        uses: actions/checkout@v4

      - name: show id
        run: echo ${{ github.run_id }}

      - name: List /
        run: ls -ahl /

      - name: Compile
        run: touch /data_1/${{ github.run_id }} && touch /data_2/${{ github.run_id }}


      - name: List data_1
        run: ls -ahl /data_1

      - name: List data_1
        run: ls -ahl /data_2

  test:
    needs: build
    runs-on: self-hosted
    container:
      image: modelcloud/gptqmodel:github-ci-v1
      volumes:
        - /tmp/${{ github.run_id }}_1:/data_1:r
        - /tmp/${{ github.run_id }}_2:/data_2:r
    strategy:
      fail-fast: false
      matrix:
        test-group:
          - gpu_group1
          - gpu_group2
    steps:
      - name: Print whl from shared dir
        run: |
          ls -ahl / || true

      - name: Print whl from shared dir
        if: matrix.test-group == 'gpu_group1'
        run: |
          ls -ahl /data_1 || true

      - name: Print whl from shared dir
        if: matrix.test-group == 'gpu_group2'
        run: |
          ls -ahl /data_1 || true
          ls -ahl /data_2 || true

      - name: Run tests group 1
        if: matrix.test-group == 'gpu_group1'
        run: |
          echo ${{ github.run_id }}
          # cat /data_1/*

      - name: Run tests group 2
        if: matrix.test-group == 'gpu_group2'
        shell: bash
        run: |
          
          echo ${{ github.run_id }}
          # cat /data_2/* || true
          ls -ahl /data_1 || true
          ls -ahl /data_2 || true
          
        
