name: Run tests

on:
  push:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup python
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
          
      - name: Install pip depends
        run: |
          pip install -U parameterized protobuf pytest ninja

      - name: Compile
        run: |
          pip install -v --no-build-isolation .

      - name: Run tests
        run: |
          cd tests
          pytest -v 
