name: Unit Tests (GPU)

on:
  push:
  repository_dispatch:
  workflow_dispatch:

env:
  CUDA_DEVICE_ORDER: PCI_BUS_ID

jobs:
  build:
    runs-on: self-hosted
    container:
      image: modelcloud/gptqmodel:github-ci-v1
      volumes:
        - /tmp/${{ github.run_id }}:/data:rw
    steps:
      - name: Checkout Codes
        uses: actions/checkout@v4

      - name: show id
        run: echo ${{ github.run_id }}

      - name: List
        run: ls -ahl /data

      - name: Compile
        run: |
          python setup.py bdist_wheel
          cp dist/*.whl /data

      - name: Compile
        run: touch /data/${{ github.run_id }}

      - name: Check whl file
        run: ls -ahl /data

  test:
    needs: build
    runs-on: self-hosted
    container:
      image: modelcloud/gptqmodel:github-ci-v1
      volumes:
        - /tmp/${{ github.run_id }}:/data:rw
    strategy:
      fail-fast: false
      matrix:
        test-group:
          - gpu_group1
          - gpu_group2
    steps:
      - name: Print whl from shared dir
        run: |
          ls -ahl /data || true

      - name: Print whl from shared dir
        run: |
          ls -ahl /data || true

      - name: Run tests group 1
        if: matrix.test-group == 'gpu_group1'
        run: pytest tests/test_perplexity.py

      - name: Run tests group 2
        if: matrix.test-group == 'gpu_group2'
        shell: bash
        run: |
          declare -a failed_tests
          
          run_test() {
              echo -e "\033[1;34mRunning $1...\033[0m"
              echo "========================================"
              pytest tests/$1
              if [ $? -ne 0 ]; then
                  failed_tests+=($1)
              fi
              echo -e "\033[1;32mFinished $1\033[0m"
              echo -e "========================================\n\n\n"
          }
          
          run_test test_lm_head.py
          run_test test_q4_exallama.py
          run_test test_q4_exallama_v2.py
          run_test test_q4_marlin.py
          run_test test_q4_triton.py
          run_test test_repacking.py
          run_test test_serialization.py
          run_test test_sharded.py
          run_test test_triton.py
          run_test test_quant_formats.py
          run_test test_q4_cuda.py
          
          if [ ${#failed_tests[@]} -ne 0 ]; then
              echo -e "\033[1;31mTests failed:\033[0m"
              for test in "${failed_tests[@]}"
              do
                  echo "$test"
              done
              exit 1
          else
              echo "All tests passed."
          fi

