name: Run tests

on:
  push:
    branches:
      - csy-runner
  repository_dispatch:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: self-hosted
    container:
      image: pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile
        run: |
          mkdir build
          pip install pytest ninja
          pip install -v --no-build-isolation .

      # - name: Get size of build directory
      #   id: dir-size
      #   run: echo "DIR_SIZE=$(du -sb build | cut -f1)" >> $GITHUB_ENV

      # - name: Cache dependencies
      #   uses: corca-ai/local-cache@v2
      #   with:
      #     path: build
      #     key: ${{ env.DIR_SIZE }}

  run-test:
    needs: build
    runs-on: self-hosted
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        test_file:
          - test_lm_head.py
          - test_perplexity.py
          - test_q4_cuda.py
          - test_q4_exallama.py
          - test_q4_exallama_v2.py
          - test_q4_marlin.py
          - test_q4_triton.py
          - test_quant_formats.py
          - test_repacking.py
          - test_serialization.py
          - test_sharded_loading.py
          - test_triton.py
    steps:
      - name: List dir
        run: |
          ls -alh

      # - name: Checkout code
      #   uses: actions/checkout@v4

      # - name: Cache dependencies
      #   uses: corca-ai/local-cache@v2
      #   with:
      #     path: build
      #     key: ${{ env.DIR_SIZE }}

      - name: Compile
        run: |
          ls -alh
          cd tests
          pip install pytest ninja
          # pip install -v --no-build-isolation .

      - name: Run tests
        run: pytest ${{ matrix.test_file }}
