name: Run tests

on:
  push:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel
    strategy:
      fail-fast: false
      matrix:
        test_file:
          - test_lm_head.py
          - test_perplexity.py
          - test_q4_cuda.py
          - test_q4_exallama.py
          - test_q4_exallama_v2.py
          - test_q4_marlin.py
          - test_q4_triton.py
          - test_quant_formats.py
          - test_repacking.py
          - test_serialization.py
          - test_sharded_loading.py
          - test_triton.py

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile
        run: |
          pip install -v --no-build-isolation .

      - name: Install test dependencies
        run: |
          pip install parameterized protobuf

      - name: Run tests
        run: python -m unittest ${{ matrix.test_file }}
