name: Unit Tests (GPU)

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      test_names:
        description: 'Input Test(s) to Run (default all)'
        required: false
        default: ''

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CUDA_DEVICE_ORDER: PCI_BUS_ID

jobs:
  build:
    runs-on: self-hosted
    container:
      image: pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel

    steps:
      - name: Find suitable GPU
        run: |
         suitable_gpu=$(nvidia-smi -L | grep "RTX 4090" | awk -F': ' '{print $1}' | sed 's/GPU //g' | while read gpu_id
          do
            mem_total=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits -i $gpu_id)
            mem_used=$(nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits -i $gpu_id)
            mem_used_pct=$((100 * mem_used / mem_total))
            if [ $mem_used_pct -lt 2 ]; then # 2 -> 98% free
              echo $gpu_id
              break
            fi
          done)
          if [ -z "$suitable_gpu" ]; then
            echo "No suitable GPU found. Exiting with error."
            exit 1
          else
            echo "CUDA_VISIBLE_DEVICES=$suitable_gpu" >> $GITHUB_ENV
            echo "CUDA_VISIBLE_DEVICES set to ${{ env.CUDA_VISIBLE_DEVICES }}"
          fi

      - name: Display Environment Variable
        run: echo "CUDA_VISIBLE_DEVICES set to ${{ env.CUDA_VISIBLE_DEVICES }}"

      - name: Checkout code
        run: apt update && apt install git && git clone --depth=1 https://github.com/ModelCloud/GPTQModel

      - name: Compile
        run: |
          pip install -U pytest ninja parameterized protobuf
          pip install -v --no-build-isolation GPTQModel


      - name: test_lm_head.py
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_lm_head') }}
        run: pytest GPTQModel/tests/test_lm_head.py

      - name: test_q4_exallama.py
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_q4_exallama') }}
        run: pytest GPTQModel/tests/test_q4_exallama.py

      - name: test_q4_exallama_v2.py
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_q4_exallama_v2') }}
        run: pytest GPTQModel/tests/test_q4_exallama_v2.py

      - name: test_q4_marlin.py
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_q4_marlin') }}
        run: pytest GPTQModel/tests/test_q4_marlin.py

      - name: test_q4_triton.py
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_q4_triton') }}
        run: pytest GPTQModel/tests/test_q4_triton.py

      - name: test_repacking.py
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_repacking') }}
        run: pytest GPTQModel/tests/test_repacking.py

      - name: test_serialization.py
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_serialization') }}
        run: pytest GPTQModel/tests/test_serialization.py

      - name: test_sharded.py
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_sharded') }}
        run: pytest GPTQModel/tests/test_sharded.py

      - name: test_triton.py
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_triton') }}
        run: pytest GPTQModel/tests/test_triton.py

      - name: test_quant_formats.py
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_quant_formats') }}
        run: pytest GPTQModel/tests/test_quant_formats.py

      - name: test_q4_cuda.py
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_q4_cuda') }}
        run: pytest GPTQModel/tests/test_q4_cuda.py

      - name: test_perplexity.py
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_perplexity') }}
        run: pytest GPTQModel/tests/test_perplexity.py


        
