name: Unit Tests (GPU)

on:
  push:
  repository_dispatch:
  workflow_dispatch:

env:
  CUDA_DEVICE_ORDER: PCI_BUS_ID

jobs:
  build:
    runs-on: self-hosted
    container:
      image: modelcloud/gptqmodel:github-ci-v1
    steps:
      - name: Checkout Codes
        uses: actions/checkout@v4

      - name: Compile
        run: touch dist/xxx

      - uses: actions/upload-artifact@v4
        with:
          path: dist

  test:
    needs: build
    runs-on: self-hosted
    container:
      image: modelcloud/gptqmodel:github-ci-v1
    strategy:
      fail-fast: false
      matrix:
        test-group:
          - gpu_group1
          - gpu_group2
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - name: Print dir
        run: |
          ls . || true

      - name: Print dir
        run: |
          ls dist || true

      - name: Run tests group 1
        if: matrix.test-group == 'gpu_group1'
        run: |
          echo ${{ github.run_id }}
          # cat /data_1/*

      - name: Run tests group 2
        if: matrix.test-group == 'gpu_group2'
        shell: bash
        run: |
          
          echo ${{ github.run_id }}
          # cat /data_2/* || true
          ls -ahl /data_1 || true
          ls -ahl /data_2 || true
          
        
