name: Unit Tests (GPU)

on:
  repository_dispatch:
  workflow_dispatch:

env:
  CUDA_DEVICE_ORDER: PCI_BUS_ID

jobs:
  build:
    runs-on: self-hosted
    container:
      image: modelcloud/gptqmodel:github-ci-v1
    steps:
      - name: Run tests group 1
        id: test_perplexity
        run: ls tests/test_perplexity.py

      - name: Run test_lm_head.py
        id: test_lm_head
        continue-on-error: true
        run: ls tests/1213m_head.py

      - name: Run test_q4_exallama.py
        id: test_q4_exallama
        continue-on-error: true
        run: ls tests/test_q4_exallama.py


      - name: Print results
        continue-on-error: true
        shell: bash
        run: |
          declare -A step_outcomes
          step_outcomes=(
            [test_perplexity]="{{ steps.test_perplexity.outcome }}"
            [test_lm_head]="{{ steps.test_lm_head.outcome }}"
            [test_q4_exallama]="{{ steps.test_q4_exallama.outcome }}"
          )
  
          for step in "${!step_outcomes[@]}"; do
            outcome="${step_outcomes[$step]}"
            if [ "$outcome" == "success" ]; then
              echo -e "\e[32m${step} Result: $outcome\e[0m"
            else
              echo -e "\e[31m${step} Result: $outcome\e[0m"
            fi
          done
