name: Unit Tests (GPU)

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      test_names:
        description: 'Input Test(s) to Run (default all)'
        required: false
        default: ''

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  DAY_OF_WEEK: Monday
  CUDA_DEVICE_ORDER: PCI_BUS_ID
  CUDA_VISIBLE_DEVICES: 0

jobs:
  build:
    runs-on: self-hosted
    container:
      image: pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile
        run: |
          pip install -U pytest ninja parameterized protobuf
          pip install -v --no-build-isolation .

      - name: test_lm_head.py
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_lm_head') }}
        run: pytest tests/test_lm_head.py

      - name: test_q4_exallama.py
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_q4_exallama') }}
        run: pytest tests/test_q4_exallama.py

      - name: test_q4_exallama_v2.py
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_q4_exallama_v2') }}
        run: pytest tests/test_q4_exallama_v2.py

      - name: test_q4_marlin.py
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_q4_marlin') }}
        run: pytest tests/test_q4_marlin.py

      - name: test_q4_triton.py
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_q4_triton') }}
        run: pytest tests/test_q4_triton.py

      - name: test_repacking.py
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_repacking') }}
        run: pytest tests/test_repacking.py

      - name: test_serialization.py
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_serialization') }}
        run: pytest tests/test_serialization.py

      - name: test_sharded.py
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_sharded') }}
        run: pytest tests/test_sharded.py

      - name: test_triton.py
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_triton') }}
        run: pytest tests/test_triton.py

      - name: test_quant_formats.py
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_quant_formats') }}
        run: pytest tests/test_quant_formats.py

      - name: test_q4_cuda.py
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_q4_cuda') }}
        run: pytest tests/test_q4_cuda.py

      - name: test_perplexity.py
        if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_perplexity') }}
        run: pytest tests/test_perplexity.py


        
